### ISSUE TITLE
Support for https testing

### ISSUE THREAD

**Issue by judeaugustinej** [eugeniy/pytest-tornado#21]
In tornado Testing for https is provide by the class AsyncHTTPSTestCase

http://www.tornadoweb.org/en/stable/_modules/tornado/testing.html#AsyncHTTPSTestCase

does pytest-tornado provide anything like that

**Comment by okin** [comment]
I don't think there is currently support for this in pytest-tornado.

From my understanding of the comment in the tornado docs the cert used for HTTPS testing has to be generated manually. Therefore I think it would make sense to let the user provide this in a way we currently handle the `app` fixture.

Do we want users to automatically have tests run against HTTP and HTTPS once a cert is provided? If so how would we handle cases where only one of these should be tested?
Or would users have to explicitely define if they want HTTP or HTTPS (i.e. by passing `http_client` or something like `https_client` as test function fixture).

**Comment by okin** [comment]
Ah, there is already PR #22. Didn't see that.

The route there is that users define if they want their clients to be http or https.
