### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Jamim** [eugeniy/pytest-tornado#45]
Hello @vidartf,

Could you please release a new version of this library or create some [milestone](https://github.com/eugeniy/pytest-tornado/milestones) in order to increase the transparency of when it can be released?

Thank you!

**Comment by vidartf** [comment]
Hi, and thanks for the input! I was considering trying to get in support for tornado 6 as well, but I guess it makes sense to do a release with tornado<6 dependency first. Does this seem reasonable to you?

**Comment by Jamim** [comment]
Yes, it does. It seems reasonable to issue some transitional release (e.g. `v0.6.0`) that will make users able to unpin `pytest` and to focus on other improvements after that.
Also, feel free to ask for help if needed.
