### ISSUE TITLE
latest release is not on pypi

### ISSUE THREAD

**Issue by andrewsw** [eugeniy/pytest-tornado#61]
version 0.8.1, tagged late May, hasn't hit pypi yet, leaving my console full of warnings (hundreds and hundreds of them!).

**Comment by vidartf** [comment]
Seems that `matrix` in the travis config overrides the `jobs` field, causing the automated deploy to fail. Looking into a fix.

**Comment by vidartf** [comment]
0.8.1 is now on PyPI, thanks for reporting! 👍

**Comment by andrewsw** [comment]
thanks!
