### ISSUE TITLE
please do not retag already released versions

### ISSUE THREAD

**Issue by anthraxx** [eugeniy/pytest-tornado#64]
Hi, thanks a lot for all your work. I would like to kindly ask to never retag git releases/tags no matter how trivial, important or unrelated the change is. Please instead release a new patch version if needed as the checksums always change.
This creates issues for distros like ours as builds fail because of pinned hashes of a specific version and packages are potentially not reproducible anymore (https://reproducible-builds.org/).
Thanks for your understanding and work

**Comment by vidartf** [comment]
Noted.
